services:
  - type: web
    name: voanh-backend
    env: python
    buildCommand: ""
    startCommand: "python main.py"
    envVars:
      - key: NOTION_TOKEN
        fromEnvVar: NOTION_TOKEN
      - key: NOTION_DATABASE_ID
        fromEnvVar: NOTION_DATABASE_ID
